powerComsumptionAll = read.csv("C:/Users/anshi/OneDrive/Documents/ExploratoryDataAnalysis/exdata_data_household_power_consumption/household_power_consumption.txt", header = TRUE, sep = ";")
powerData = subset(powerComsumptionAll, powerComsumptionAll$Date == "1/2/2007" | powerComsumptionAll$Date == "2/2/2007")
powerData$Global_active_power = as.numeric(as.character(powerData$Global_active_power))
dateTimeVector = paste(powerData$Date, powerData$Time)
dateTimeVector = strptime(dateTimeVector, format = "%d/%m/%Y %H:%M:%S")
powerData$Sub_metering_1 = as.numeric(as.character(powerData$Sub_metering_1))
powerData$Sub_metering_2 = as.numeric(as.character(powerData$Sub_metering_2))
powerData$Voltage = as.numeric(as.character(powerData$Voltage))
powerData$Global_reactive_power = as.numeric(as.character(powerData$Global_reactive_power))
par(mfrow = c(2,2))
plot(dateTimeVector, powerData$Global_active_power, type="l", xlab="", ylab = "Global Active Power")
plot(dateTimeVector, powerData$Voltage, xlab="datetime", ylab="Voltage", type="l")
plot(dateTimeVector, powerData$Sub_metering_1, col="black", type="l", xlab ="", ylab="Energy sub metering")
points(dateTimeVector,powerData$Sub_metering_2, col="red", type = "l")
points(dateTimeVector,powerData$Sub_metering_3, col="blue", type = "l")
legend("topright", pch = "___", col= c("black", "red","blue"), legend = c("Sub metering_1", "Sub metering_2", "Sub metering_3" ), bty='n')
plot(dateTimeVector, powerData$Global_reactive_power, xlab="datetime", ylab="Global_Reactive_Power", type="l")
dev.copy(png, "plot4.png", height = 480, width = 480)
dev.off()